---
- name: install common needed packages
  tags:
    - install
    - packages
    - ntp
  pacman:
    name: ntp
    state: present

- name: configure ntp daemon
  tags:
    - install
    - packages
    - update
    - ntp
  copy:
    src: ntp-archlinux.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp

- name: enable ntp
  tags:
    - install
    - ntp
  service:
    name: ntpd
    enabled: yes
  notify: restart ntp