---
- name: install ntp packages
  tags:
    - install
    - packages
    - ntp
  apt:
    pkg: ntp
    state: present

- name: configure ntp daemon
  tags:
    - install
    - packages
    - update
    - ntp
  copy:
    src: ntp-debian.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp

- name: enable ntp
  tags:
    - install
    - ntp
  service:
    name: ntp
    enabled: yes
  notify: restart ntp