---
- name: check if advanced configuration for ssh is available
  tags:
    - install
    - update
    - user
    - ssh
  set_fact:
    ssh_enable_advanced_configuration: True
  when: ansible_lsb.id == "Archlinux"

- name: write sshd configuration
  tags:
    - install
    - update
    - user
    - ssh
  template:
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

- name: write ssh configuration
  tags:
    - install
    - update
    - user
    - ssh
  template:
    src: ssh_config.j2
    dest: "/etc/ssh/ssh_config"
    owner: root
    group: root
    mode: 0644
  notify: restart sshd